import type { Contact, Deal, EmailLog } from '../types';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 1,
    firstName: 'Sarah',
    lastName: 'Chen',
    fullName: 'Sarah Chen',
    email: 'sarah.chen@techcorp.io',
    phone: '+1-415-555-0101',
    company: 'TechCorp',
    title: 'VP of Engineering',
    source: 'LinkedIn',
    tags: ['hot-lead', 'enterprise'],
    notes: 'Met at React Summit. Very interested in the API tier.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    firstName: 'Marcus',
    lastName: 'Reed',
    fullName: 'Marcus Reed',
    email: 'mreed@growthly.com',
    phone: '+1-212-555-0182',
    company: 'Growthly',
    title: 'CEO',
    source: 'Cold Outreach',
    tags: ['decision-maker', 'startup'],
    notes: 'Responded to 3rd follow-up email. Budget confirmed ~$40k/yr.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    firstName: 'Priya',
    lastName: 'Sharma',
    fullName: 'Priya Sharma',
    email: 'priya@scalenow.co',
    phone: '+1-650-555-0237',
    company: 'ScaleNow',
    title: 'Head of Product',
    source: 'Referral',
    tags: ['warm-lead'],
    notes: 'Referred by Marcus. Looking to replace Salesforce.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    firstName: 'Daniel',
    lastName: 'Torres',
    fullName: 'Daniel Torres',
    email: 'dtorres@launchpad.io',
    phone: '+1-310-555-0093',
    company: 'Launchpad.io',
    title: 'CTO',
    source: 'Conference',
    tags: ['enterprise', 'technical'],
    notes: 'Deep technical requirements. Needs SOC2 compliance.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    firstName: 'Emma',
    lastName: 'Watson',
    fullName: 'Emma Watson',
    email: 'emma.w@brightmedia.com',
    phone: '+1-617-555-0344',
    company: 'BrightMedia',
    title: 'Marketing Director',
    source: 'Inbound',
    tags: ['smb', 'warm-lead'],
    notes: 'Downloaded whitepaper. Booked a demo call.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    firstName: 'Rachel',
    lastName: 'Kim',
    fullName: 'Rachel Kim',
    email: 'rkim@healthtech.ai',
    phone: '+1-404-555-0391',
    company: 'HealthTech AI',
    title: 'VP Sales',
    source: 'Referral',
    tags: ['hot-lead', 'healthcare'],
    notes: 'HIPAA compliance is non-negotiable. Budget approved Q1.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 1,
    title: 'TechCorp — API Integration Suite',
    contactId: 1,
    contactName: 'Sarah Chen',
    value: 85000,
    stage: 'QUALIFIED',
    priority: 'HIGH',
    expectedCloseDate: '2026-09-27',
    notes: 'POC completed. Legal review in progress.',
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Growthly — CRM Starter Plan',
    contactId: 2,
    contactName: 'Marcus Reed',
    value: 24000,
    stage: 'PROPOSAL',
    priority: 'HIGH',
    expectedCloseDate: '2026-09-11',
    notes: 'Proposal sent. Waiting for board approval.',
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'ScaleNow — Enterprise License',
    contactId: 3,
    contactName: 'Priya Sharma',
    value: 120000,
    stage: 'CONTACTED',
    priority: 'MEDIUM',
    expectedCloseDate: '2026-10-27',
    notes: 'Discovery call done. Sending SOW next week.',
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Launchpad — Security Package',
    contactId: 4,
    contactName: 'Daniel Torres',
    value: 45000,
    stage: 'LEAD',
    priority: 'MEDIUM',
    expectedCloseDate: '2026-11-26',
    notes: 'Initial contact made. SOC2 docs requested.',
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: 'HealthTech AI — Compliance Module',
    contactId: 6,
    contactName: 'Rachel Kim',
    value: 95000,
    stage: 'WON',
    priority: 'HIGH',
    expectedCloseDate: '2026-08-23',
    notes: 'Contract signed! Implementation starts next Monday.',
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    title: 'CloudPilot — Startup Plan',
    value: 8400,
    stage: 'LOST',
    priority: 'LOW',
    expectedCloseDate: '2026-08-18',
    notes: 'Went with a competitor due to pricing.',
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_EMAILS: EmailLog[] = [
  {
    id: 1,
    contactId: 1,
    contactName: 'Sarah Chen',
    dealId: 1,
    dealTitle: 'TechCorp — API Integration Suite',
    subject: 'Following up on our API integration discussion',
    bodyPreview: 'Hi Sarah, great speaking with you at React Summit! I wanted to follow up on the API integration details we discussed...',
    status: 'REPLIED',
    sentAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    openedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    repliedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 2,
    contactId: 2,
    contactName: 'Marcus Reed',
    dealId: 2,
    dealTitle: 'Growthly — CRM Starter Plan',
    subject: 'Your Custom CRM Proposal — Growthly x MiniCRM',
    bodyPreview: "Hi Marcus, as promised, I've attached the proposal tailored to Growthly's requirements...",
    status: 'OPENED',
    sentAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    openedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 3,
    contactId: 3,
    contactName: 'Priya Sharma',
    dealId: 3,
    dealTitle: 'ScaleNow — Enterprise License',
    subject: 'Cold Intro — Replace Salesforce at Half the Cost',
    bodyPreview: "Hi Priya, Marcus mentioned you're evaluating CRM options. We've helped 3 similar companies migrate from Salesforce...",
    status: 'SENT',
    sentAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];
